before_script:
  - whoami
  - hostname
  - docker info
  - apt-get update
  - apt-get install docker.io
build_image:
  script:
    - docker build -t orly-generator:0.1 -t orly-generator:latest .
    - docker rm -f orly-generator
    - docker run -d --name orly-generator -e "SERVICE_TAGS=traefik.enable=false" orly-generator
  tags:
    - docker